name: Caller Workflow

on:
  pull_request:
    branches:
      - dev

jobs:
  call-workflow:
    uses: ./.github/workflows/called_workflow.yml

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/called_workflow.yml
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.PAT }}