name: Caller Workflow

on:
  push:
    branches:
      - dev

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/reusable_workflow_no_secret.yml
    with:
      name: Andrews Tate
      age: 56
      address: Stradă Drumul Bisericii 50, Voluntari 077190, Roumanie