name: Caller Workflow

on:
  pull_request:
    branches:
      - int

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/called_workflow.yml
    with:
      config-path: .github/labeler.yml
      repo_token: ${{ secrets.PAT }}
    secrets:
      token: ${{ secrets.PAT }}