on:
  pull_request:
    branches:
      - int
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: aab-saphir/tuto_workflow
          token: ${{ secrets.PAT }}
          ref: dev
      - id: foo
        uses: ./.github/actions/hello-world-composite-action
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash