name: Create PR int
on:
  push:
    branches:
      - dev
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: aab-saphir/tuto_workflow
          token: ${{ secrets.PAT }}
          ref: dev

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Updateauthor information
        run: echo $({env.GIT_COMMIT_AUTHOR_NAME}) > AUTHOR

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          committer: aab-saphir <abdelkader.addabousekrane@ext.leroymerlin.fr>
          author: aab-saphir <abdelkader.addabousekrane@ext.leroymerlin.fr>
          branch: int
          base: dev
          delete-branch: false
          title: 'Raise PR'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request