name: echo param
on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: NO_PROVIDED
      age:
        required: false
        type: int
        default: 0
      address:
        required: false
        type: string
        default: NO_ADDRESS
jobs:
  call_character:
    runs_on: ubuntu-latest
    steps:
    - run: pwd
      shell: bash

    - name: presentation
      run: |
        echo "je m appelle" ${{ inputs.name }}
        echo "j ai" ${{ inputs.age }} "ans"
        echo "j habite au" ${{ inputs.address }}
      shell: bash
